# ...
steps:
  - uses: actions/download-artifact@v4'
    with:
      name: firebase-hosting-files
      path: './build'
  - uses: 'firebase/hosting-deploy@v0'
    with:
      repoToken: '${{ secrets.GITHUB_TOKEN }}'
      projectId: 'my-student-portal-e4922'  <-- Check indentation here
      channelId: 'preview-${{ github.event.number }}'
      # ...